#Programmed by: Gavin Bernard
#Date: 2/19/2022

import os

#writes text to file; initial check is to check if directory has '\' at end
def write_file(text_list, direct):
    if direct[-1] != '\\':
        direct += '\\'
    
    with open(direct + 'validate.txt', 'w') as file:
        file.truncate(0)
        for text in text_list:
            file.write(text + '\n')

    file.close()

#reads text file generated by user
def read_file(direct):
    if direct[-1] != '\\':
        direct += '\\'
    
    file = open(direct + 'validate.txt')

    line = file.readlines()

    for text in line:
        print(text)

    file.close()

#checks if directory exists; if not return false and tell user input is invalid
def check_exist(path):
    check = os.path.isdir(path)

    if not check:
        print("The directory you entered is invalid. Please enter a valid directory.")
        
    return check

#starts the program; contains most of the code
def start():
    print("\t" + "[Welcome to the Directory Validation System]")

    #as much as I want to just give a list of directories, the point of this program is to validate the existence of one
    real = False
    info = []

    #get real
    while not real:
        directory = input("Please enter the directory you would like to validate: ")
        real = check_exist(directory)

    print("Directory validation successful! The program now requires your user info.")
    
    info.append("Name: " + input("Please enter your name. "))
    info.append("Address: " + input("Now enter your address. "))
    info.append("Phone Number: " + input("Finally, enter your phone number. "))

    write_file(info, directory)

    ans = ''
    
    while ans.capitalize() != 'Y' and ans.capitalize() != 'N':
        ans = input("Your file has been created! Would you like to view it? (Y/N) ")

    if ans == 'Y':
        print("\t" + "[Your Results!]")
        read_file(directory)

#print(check_exist(r'C:\Users\gavin\Desktop'))
       
start()
